# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1080, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1080, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(400, 400))
        self.centralwidget.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(1080, 720))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(-10, 0, 1071, 661))
        self.label.setMaximumSize(QtCore.QSize(1080, 720))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Imagenes/Fondo.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setGeometry(QtCore.QRect(-60, 60, 161, 91))
        self.pushButton_7.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Imagenes/smart greenhouse (3).jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setIconSize(QtCore.QSize(162, 100))
        self.pushButton_7.setObjectName("pushButton_7")
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setGeometry(QtCore.QRect(300, 50, 141, 31))
        self.comboBox.setObjectName("comboBox")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(130, 50, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setGeometry(QtCore.QRect(600, 52, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setItalic(True)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setGeometry(QtCore.QRect(50, 230, 950, 410))
        self.scrollArea.setMinimumSize(QtCore.QSize(950, 410))
        self.scrollArea.setMaximumSize(QtCore.QSize(950, 410))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 934, 408))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 0, 911, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #75bf7b; /* Color de fondo */\n"
"    color: white; /* Color del texto */\n"
"    border: 3px solid #59ad4b; /* Color del borde */\n"
"    border-radius: 7px; /* Bordes redondeados */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(52, 152, 219, 0.7); /* Color translúcido al presionar */\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(True)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: #75bf7b; /* Color de fondo */\n"
"    color: white; /* Color del texto */\n"
"    border: 3px solid #59ad4b; /* Color del borde */\n"
"    border-radius: 7px; /* Bordes redondeados */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(52, 152, 219, 0.7); /* Color translúcido al presionar */\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(True)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #75bf7b; /* Color de fondo */\n"
"    color: white; /* Color del texto */\n"
"    border: 3px solid #59ad4b; /* Color del borde */\n"
"    border-radius: 7px; /* Bordes redondeados */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(52, 152, 219, 0.7); /* Color translúcido al presionar */\n"
"}")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #75bf7b; /* Color de fondo */\n"
"    color: white; /* Color del texto */\n"
"    border: 3px solid #59ad4b; /* Color del borde */\n"
"    border-radius: 7px; /* Bordes redondeados */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(52, 152, 219, 0.7); /* Color translúcido al presionar */\n"
"}")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #75bf7b; /* Color de fondo */\n"
"    color: white; /* Color del texto */\n"
"    border: 3px solid #59ad4b; /* Color del borde */\n"
"    border-radius: 7px; /* Bordes redondeados */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(52, 152, 219, 0.7); /* Color translúcido al presionar */\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #75bf7b; /* Color de fondo */\n"
"    color: white; /* Color del texto */\n"
"    border: 3px solid #59ad4b; /* Color del borde */\n"
"    border-radius: 7px; /* Bordes redondeados */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(52, 152, 219, 0.7); /* Color translúcido al presionar */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_8.clicked.connect(MainWindow.ordenar_botones) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Ordenar por"))
        self.pushButton_8.setText(_translate("MainWindow", "Actualizar"))
        self.pushButton_3.setText(_translate("MainWindow", "Amapola"))
        self.pushButton_6.setText(_translate("MainWindow", "Rosa"))
        self.pushButton.setText(_translate("MainWindow", "xxxxx"))